/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as SetupsRouteImport } from './routes/setups'
import { Route as ScorecardRouteImport } from './routes/scorecard'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AnaloguesRouteImport } from './routes/analogues'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TickersIndexRouteImport } from './routes/tickers.index'
import { Route as TickersSymbolRouteImport } from './routes/tickers.$symbol'
import { Route as SignalIdRouteImport } from './routes/signal.$id'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as AdminBrokerSymbolsRouteImport } from './routes/admin.broker-symbols'
import { Route as AuthenticatedBrokerRouteImport } from './routes/_authenticated/broker'
import { Route as AuthenticatedBridgeRouteImport } from './routes/_authenticated/bridge'
import { Route as AuthenticatedBlotterRouteImport } from './routes/_authenticated/blotter'
import { Route as ApiPublicStreamQuotesRouteImport } from './routes/api/public/stream/quotes'
import { Route as ApiPublicHooksIngestNewsRouteImport } from './routes/api/public/hooks/ingest-news'
import { Route as ApiPublicHooksEvaluateSignalsRouteImport } from './routes/api/public/hooks/evaluate-signals'
import { Route as ApiPublicHooksBackfillBenchmarksRouteImport } from './routes/api/public/hooks/backfill-benchmarks'
import { Route as ApiPublicBridgePositionsRouteImport } from './routes/api/public/bridge/positions'
import { Route as ApiPublicBridgeOrdersRouteImport } from './routes/api/public/bridge/orders'
import { Route as ApiPublicBridgeInstructionsRouteImport } from './routes/api/public/bridge/instructions'
import { Route as ApiPublicBridgeFillsRouteImport } from './routes/api/public/bridge/fills'
import { Route as ApiPublicBridgeDealsRouteImport } from './routes/api/public/bridge/deals'
import { Route as ApiPublicBridgeAccountRouteImport } from './routes/api/public/bridge/account'
import { Route as ApiPublicBridgeInstructionsIdResultRouteImport } from './routes/api/public/bridge/instructions.$id.result'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupsRoute = SetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardRoute = ScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaloguesRoute = AnaloguesRouteImport.update({
  id: '/analogues',
  path: '/analogues',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TickersIndexRoute = TickersIndexRouteImport.update({
  id: '/tickers/',
  path: '/tickers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TickersSymbolRoute = TickersSymbolRouteImport.update({
  id: '/tickers/$symbol',
  path: '/tickers/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalIdRoute = SignalIdRouteImport.update({
  id: '/signal/$id',
  path: '/signal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrokerSymbolsRoute = AdminBrokerSymbolsRouteImport.update({
  id: '/admin/broker-symbols',
  path: '/admin/broker-symbols',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBrokerRoute = AuthenticatedBrokerRouteImport.update({
  id: '/broker',
  path: '/broker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBridgeRoute = AuthenticatedBridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlotterRoute = AuthenticatedBlotterRouteImport.update({
  id: '/blotter',
  path: '/blotter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicStreamQuotesRoute = ApiPublicStreamQuotesRouteImport.update({
  id: '/api/public/stream/quotes',
  path: '/api/public/stream/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestNewsRoute =
  ApiPublicHooksIngestNewsRouteImport.update({
    id: '/api/public/hooks/ingest-news',
    path: '/api/public/hooks/ingest-news',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEvaluateSignalsRoute =
  ApiPublicHooksEvaluateSignalsRouteImport.update({
    id: '/api/public/hooks/evaluate-signals',
    path: '/api/public/hooks/evaluate-signals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillBenchmarksRoute =
  ApiPublicHooksBackfillBenchmarksRouteImport.update({
    id: '/api/public/hooks/backfill-benchmarks',
    path: '/api/public/hooks/backfill-benchmarks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgePositionsRoute =
  ApiPublicBridgePositionsRouteImport.update({
    id: '/api/public/bridge/positions',
    path: '/api/public/bridge/positions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeOrdersRoute = ApiPublicBridgeOrdersRouteImport.update({
  id: '/api/public/bridge/orders',
  path: '/api/public/bridge/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeInstructionsRoute =
  ApiPublicBridgeInstructionsRouteImport.update({
    id: '/api/public/bridge/instructions',
    path: '/api/public/bridge/instructions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeFillsRoute = ApiPublicBridgeFillsRouteImport.update({
  id: '/api/public/bridge/fills',
  path: '/api/public/bridge/fills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeDealsRoute = ApiPublicBridgeDealsRouteImport.update({
  id: '/api/public/bridge/deals',
  path: '/api/public/bridge/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeAccountRoute = ApiPublicBridgeAccountRouteImport.update({
  id: '/api/public/bridge/account',
  path: '/api/public/bridge/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeInstructionsIdResultRoute =
  ApiPublicBridgeInstructionsIdResultRouteImport.update({
    id: '/$id/result',
    path: '/$id/result',
    getParentRoute: () => ApiPublicBridgeInstructionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analogues': typeof AnaloguesRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/manual': typeof ManualRoute
  '/playbooks': typeof PlaybooksRoute
  '/scorecard': typeof ScorecardRoute
  '/setups': typeof SetupsRoute
  '/tracker': typeof TrackerRoute
  '/watchlist': typeof WatchlistRoute
  '/blotter': typeof AuthenticatedBlotterRoute
  '/bridge': typeof AuthenticatedBridgeRoute
  '/broker': typeof AuthenticatedBrokerRoute
  '/admin/broker-symbols': typeof AdminBrokerSymbolsRoute
  '/event/$id': typeof EventIdRoute
  '/signal/$id': typeof SignalIdRoute
  '/tickers/$symbol': typeof TickersSymbolRoute
  '/tickers/': typeof TickersIndexRoute
  '/api/public/bridge/account': typeof ApiPublicBridgeAccountRoute
  '/api/public/bridge/deals': typeof ApiPublicBridgeDealsRoute
  '/api/public/bridge/fills': typeof ApiPublicBridgeFillsRoute
  '/api/public/bridge/instructions': typeof ApiPublicBridgeInstructionsRouteWithChildren
  '/api/public/bridge/orders': typeof ApiPublicBridgeOrdersRoute
  '/api/public/bridge/positions': typeof ApiPublicBridgePositionsRoute
  '/api/public/hooks/backfill-benchmarks': typeof ApiPublicHooksBackfillBenchmarksRoute
  '/api/public/hooks/evaluate-signals': typeof ApiPublicHooksEvaluateSignalsRoute
  '/api/public/hooks/ingest-news': typeof ApiPublicHooksIngestNewsRoute
  '/api/public/stream/quotes': typeof ApiPublicStreamQuotesRoute
  '/api/public/bridge/instructions/$id/result': typeof ApiPublicBridgeInstructionsIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analogues': typeof AnaloguesRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/manual': typeof ManualRoute
  '/playbooks': typeof PlaybooksRoute
  '/scorecard': typeof ScorecardRoute
  '/setups': typeof SetupsRoute
  '/tracker': typeof TrackerRoute
  '/watchlist': typeof WatchlistRoute
  '/blotter': typeof AuthenticatedBlotterRoute
  '/bridge': typeof AuthenticatedBridgeRoute
  '/broker': typeof AuthenticatedBrokerRoute
  '/admin/broker-symbols': typeof AdminBrokerSymbolsRoute
  '/event/$id': typeof EventIdRoute
  '/signal/$id': typeof SignalIdRoute
  '/tickers/$symbol': typeof TickersSymbolRoute
  '/tickers': typeof TickersIndexRoute
  '/api/public/bridge/account': typeof ApiPublicBridgeAccountRoute
  '/api/public/bridge/deals': typeof ApiPublicBridgeDealsRoute
  '/api/public/bridge/fills': typeof ApiPublicBridgeFillsRoute
  '/api/public/bridge/instructions': typeof ApiPublicBridgeInstructionsRouteWithChildren
  '/api/public/bridge/orders': typeof ApiPublicBridgeOrdersRoute
  '/api/public/bridge/positions': typeof ApiPublicBridgePositionsRoute
  '/api/public/hooks/backfill-benchmarks': typeof ApiPublicHooksBackfillBenchmarksRoute
  '/api/public/hooks/evaluate-signals': typeof ApiPublicHooksEvaluateSignalsRoute
  '/api/public/hooks/ingest-news': typeof ApiPublicHooksIngestNewsRoute
  '/api/public/stream/quotes': typeof ApiPublicStreamQuotesRoute
  '/api/public/bridge/instructions/$id/result': typeof ApiPublicBridgeInstructionsIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analogues': typeof AnaloguesRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/manual': typeof ManualRoute
  '/playbooks': typeof PlaybooksRoute
  '/scorecard': typeof ScorecardRoute
  '/setups': typeof SetupsRoute
  '/tracker': typeof TrackerRoute
  '/watchlist': typeof WatchlistRoute
  '/_authenticated/blotter': typeof AuthenticatedBlotterRoute
  '/_authenticated/bridge': typeof AuthenticatedBridgeRoute
  '/_authenticated/broker': typeof AuthenticatedBrokerRoute
  '/admin/broker-symbols': typeof AdminBrokerSymbolsRoute
  '/event/$id': typeof EventIdRoute
  '/signal/$id': typeof SignalIdRoute
  '/tickers/$symbol': typeof TickersSymbolRoute
  '/tickers/': typeof TickersIndexRoute
  '/api/public/bridge/account': typeof ApiPublicBridgeAccountRoute
  '/api/public/bridge/deals': typeof ApiPublicBridgeDealsRoute
  '/api/public/bridge/fills': typeof ApiPublicBridgeFillsRoute
  '/api/public/bridge/instructions': typeof ApiPublicBridgeInstructionsRouteWithChildren
  '/api/public/bridge/orders': typeof ApiPublicBridgeOrdersRoute
  '/api/public/bridge/positions': typeof ApiPublicBridgePositionsRoute
  '/api/public/hooks/backfill-benchmarks': typeof ApiPublicHooksBackfillBenchmarksRoute
  '/api/public/hooks/evaluate-signals': typeof ApiPublicHooksEvaluateSignalsRoute
  '/api/public/hooks/ingest-news': typeof ApiPublicHooksIngestNewsRoute
  '/api/public/stream/quotes': typeof ApiPublicStreamQuotesRoute
  '/api/public/bridge/instructions/$id/result': typeof ApiPublicBridgeInstructionsIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analogues'
    | '/analyze'
    | '/auth'
    | '/calendar'
    | '/manual'
    | '/playbooks'
    | '/scorecard'
    | '/setups'
    | '/tracker'
    | '/watchlist'
    | '/blotter'
    | '/bridge'
    | '/broker'
    | '/admin/broker-symbols'
    | '/event/$id'
    | '/signal/$id'
    | '/tickers/$symbol'
    | '/tickers/'
    | '/api/public/bridge/account'
    | '/api/public/bridge/deals'
    | '/api/public/bridge/fills'
    | '/api/public/bridge/instructions'
    | '/api/public/bridge/orders'
    | '/api/public/bridge/positions'
    | '/api/public/hooks/backfill-benchmarks'
    | '/api/public/hooks/evaluate-signals'
    | '/api/public/hooks/ingest-news'
    | '/api/public/stream/quotes'
    | '/api/public/bridge/instructions/$id/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analogues'
    | '/analyze'
    | '/auth'
    | '/calendar'
    | '/manual'
    | '/playbooks'
    | '/scorecard'
    | '/setups'
    | '/tracker'
    | '/watchlist'
    | '/blotter'
    | '/bridge'
    | '/broker'
    | '/admin/broker-symbols'
    | '/event/$id'
    | '/signal/$id'
    | '/tickers/$symbol'
    | '/tickers'
    | '/api/public/bridge/account'
    | '/api/public/bridge/deals'
    | '/api/public/bridge/fills'
    | '/api/public/bridge/instructions'
    | '/api/public/bridge/orders'
    | '/api/public/bridge/positions'
    | '/api/public/hooks/backfill-benchmarks'
    | '/api/public/hooks/evaluate-signals'
    | '/api/public/hooks/ingest-news'
    | '/api/public/stream/quotes'
    | '/api/public/bridge/instructions/$id/result'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analogues'
    | '/analyze'
    | '/auth'
    | '/calendar'
    | '/manual'
    | '/playbooks'
    | '/scorecard'
    | '/setups'
    | '/tracker'
    | '/watchlist'
    | '/_authenticated/blotter'
    | '/_authenticated/bridge'
    | '/_authenticated/broker'
    | '/admin/broker-symbols'
    | '/event/$id'
    | '/signal/$id'
    | '/tickers/$symbol'
    | '/tickers/'
    | '/api/public/bridge/account'
    | '/api/public/bridge/deals'
    | '/api/public/bridge/fills'
    | '/api/public/bridge/instructions'
    | '/api/public/bridge/orders'
    | '/api/public/bridge/positions'
    | '/api/public/hooks/backfill-benchmarks'
    | '/api/public/hooks/evaluate-signals'
    | '/api/public/hooks/ingest-news'
    | '/api/public/stream/quotes'
    | '/api/public/bridge/instructions/$id/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnaloguesRoute: typeof AnaloguesRoute
  AnalyzeRoute: typeof AnalyzeRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  ManualRoute: typeof ManualRoute
  PlaybooksRoute: typeof PlaybooksRoute
  ScorecardRoute: typeof ScorecardRoute
  SetupsRoute: typeof SetupsRoute
  TrackerRoute: typeof TrackerRoute
  WatchlistRoute: typeof WatchlistRoute
  AdminBrokerSymbolsRoute: typeof AdminBrokerSymbolsRoute
  EventIdRoute: typeof EventIdRoute
  SignalIdRoute: typeof SignalIdRoute
  TickersSymbolRoute: typeof TickersSymbolRoute
  TickersIndexRoute: typeof TickersIndexRoute
  ApiPublicBridgeAccountRoute: typeof ApiPublicBridgeAccountRoute
  ApiPublicBridgeDealsRoute: typeof ApiPublicBridgeDealsRoute
  ApiPublicBridgeFillsRoute: typeof ApiPublicBridgeFillsRoute
  ApiPublicBridgeInstructionsRoute: typeof ApiPublicBridgeInstructionsRouteWithChildren
  ApiPublicBridgeOrdersRoute: typeof ApiPublicBridgeOrdersRoute
  ApiPublicBridgePositionsRoute: typeof ApiPublicBridgePositionsRoute
  ApiPublicHooksBackfillBenchmarksRoute: typeof ApiPublicHooksBackfillBenchmarksRoute
  ApiPublicHooksEvaluateSignalsRoute: typeof ApiPublicHooksEvaluateSignalsRoute
  ApiPublicHooksIngestNewsRoute: typeof ApiPublicHooksIngestNewsRoute
  ApiPublicStreamQuotesRoute: typeof ApiPublicStreamQuotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setups': {
      id: '/setups'
      path: '/setups'
      fullPath: '/setups'
      preLoaderRoute: typeof SetupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecard': {
      id: '/scorecard'
      path: '/scorecard'
      fullPath: '/scorecard'
      preLoaderRoute: typeof ScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analogues': {
      id: '/analogues'
      path: '/analogues'
      fullPath: '/analogues'
      preLoaderRoute: typeof AnaloguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickers/': {
      id: '/tickers/'
      path: '/tickers'
      fullPath: '/tickers/'
      preLoaderRoute: typeof TickersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickers/$symbol': {
      id: '/tickers/$symbol'
      path: '/tickers/$symbol'
      fullPath: '/tickers/$symbol'
      preLoaderRoute: typeof TickersSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal/$id': {
      id: '/signal/$id'
      path: '/signal/$id'
      fullPath: '/signal/$id'
      preLoaderRoute: typeof SignalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/broker-symbols': {
      id: '/admin/broker-symbols'
      path: '/admin/broker-symbols'
      fullPath: '/admin/broker-symbols'
      preLoaderRoute: typeof AdminBrokerSymbolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/broker': {
      id: '/_authenticated/broker'
      path: '/broker'
      fullPath: '/broker'
      preLoaderRoute: typeof AuthenticatedBrokerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bridge': {
      id: '/_authenticated/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof AuthenticatedBridgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blotter': {
      id: '/_authenticated/blotter'
      path: '/blotter'
      fullPath: '/blotter'
      preLoaderRoute: typeof AuthenticatedBlotterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stream/quotes': {
      id: '/api/public/stream/quotes'
      path: '/api/public/stream/quotes'
      fullPath: '/api/public/stream/quotes'
      preLoaderRoute: typeof ApiPublicStreamQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-news': {
      id: '/api/public/hooks/ingest-news'
      path: '/api/public/hooks/ingest-news'
      fullPath: '/api/public/hooks/ingest-news'
      preLoaderRoute: typeof ApiPublicHooksIngestNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/evaluate-signals': {
      id: '/api/public/hooks/evaluate-signals'
      path: '/api/public/hooks/evaluate-signals'
      fullPath: '/api/public/hooks/evaluate-signals'
      preLoaderRoute: typeof ApiPublicHooksEvaluateSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-benchmarks': {
      id: '/api/public/hooks/backfill-benchmarks'
      path: '/api/public/hooks/backfill-benchmarks'
      fullPath: '/api/public/hooks/backfill-benchmarks'
      preLoaderRoute: typeof ApiPublicHooksBackfillBenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/positions': {
      id: '/api/public/bridge/positions'
      path: '/api/public/bridge/positions'
      fullPath: '/api/public/bridge/positions'
      preLoaderRoute: typeof ApiPublicBridgePositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/orders': {
      id: '/api/public/bridge/orders'
      path: '/api/public/bridge/orders'
      fullPath: '/api/public/bridge/orders'
      preLoaderRoute: typeof ApiPublicBridgeOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/instructions': {
      id: '/api/public/bridge/instructions'
      path: '/api/public/bridge/instructions'
      fullPath: '/api/public/bridge/instructions'
      preLoaderRoute: typeof ApiPublicBridgeInstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/fills': {
      id: '/api/public/bridge/fills'
      path: '/api/public/bridge/fills'
      fullPath: '/api/public/bridge/fills'
      preLoaderRoute: typeof ApiPublicBridgeFillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/deals': {
      id: '/api/public/bridge/deals'
      path: '/api/public/bridge/deals'
      fullPath: '/api/public/bridge/deals'
      preLoaderRoute: typeof ApiPublicBridgeDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/account': {
      id: '/api/public/bridge/account'
      path: '/api/public/bridge/account'
      fullPath: '/api/public/bridge/account'
      preLoaderRoute: typeof ApiPublicBridgeAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/instructions/$id/result': {
      id: '/api/public/bridge/instructions/$id/result'
      path: '/$id/result'
      fullPath: '/api/public/bridge/instructions/$id/result'
      preLoaderRoute: typeof ApiPublicBridgeInstructionsIdResultRouteImport
      parentRoute: typeof ApiPublicBridgeInstructionsRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBlotterRoute: typeof AuthenticatedBlotterRoute
  AuthenticatedBridgeRoute: typeof AuthenticatedBridgeRoute
  AuthenticatedBrokerRoute: typeof AuthenticatedBrokerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBlotterRoute: AuthenticatedBlotterRoute,
  AuthenticatedBridgeRoute: AuthenticatedBridgeRoute,
  AuthenticatedBrokerRoute: AuthenticatedBrokerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicBridgeInstructionsRouteChildren {
  ApiPublicBridgeInstructionsIdResultRoute: typeof ApiPublicBridgeInstructionsIdResultRoute
}

const ApiPublicBridgeInstructionsRouteChildren: ApiPublicBridgeInstructionsRouteChildren =
  {
    ApiPublicBridgeInstructionsIdResultRoute:
      ApiPublicBridgeInstructionsIdResultRoute,
  }

const ApiPublicBridgeInstructionsRouteWithChildren =
  ApiPublicBridgeInstructionsRoute._addFileChildren(
    ApiPublicBridgeInstructionsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnaloguesRoute: AnaloguesRoute,
  AnalyzeRoute: AnalyzeRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  ManualRoute: ManualRoute,
  PlaybooksRoute: PlaybooksRoute,
  ScorecardRoute: ScorecardRoute,
  SetupsRoute: SetupsRoute,
  TrackerRoute: TrackerRoute,
  WatchlistRoute: WatchlistRoute,
  AdminBrokerSymbolsRoute: AdminBrokerSymbolsRoute,
  EventIdRoute: EventIdRoute,
  SignalIdRoute: SignalIdRoute,
  TickersSymbolRoute: TickersSymbolRoute,
  TickersIndexRoute: TickersIndexRoute,
  ApiPublicBridgeAccountRoute: ApiPublicBridgeAccountRoute,
  ApiPublicBridgeDealsRoute: ApiPublicBridgeDealsRoute,
  ApiPublicBridgeFillsRoute: ApiPublicBridgeFillsRoute,
  ApiPublicBridgeInstructionsRoute:
    ApiPublicBridgeInstructionsRouteWithChildren,
  ApiPublicBridgeOrdersRoute: ApiPublicBridgeOrdersRoute,
  ApiPublicBridgePositionsRoute: ApiPublicBridgePositionsRoute,
  ApiPublicHooksBackfillBenchmarksRoute: ApiPublicHooksBackfillBenchmarksRoute,
  ApiPublicHooksEvaluateSignalsRoute: ApiPublicHooksEvaluateSignalsRoute,
  ApiPublicHooksIngestNewsRoute: ApiPublicHooksIngestNewsRoute,
  ApiPublicStreamQuotesRoute: ApiPublicStreamQuotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
